# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-09-19 11:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='user',
            name='imei_idx',
        ),
        migrations.RenameField(
            model_name='user',
            old_name='ii',
            new_name='i_i',
        ),
        migrations.AddIndex(
            model_name='user',
            index=models.Index(fields=['i_i'], name='imei_idx'),
        ),
    ]
