# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-09-19 14:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_auto_20180919_1552'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='user',
            name='android_id_idx',
        ),
        migrations.RemoveIndex(
            model_name='user',
            name='MAC_Address_idx',
        ),
        migrations.RemoveIndex(
            model_name='user',
            name='imei_idx',
        ),
        migrations.RenameField(
            model_name='user',
            old_name='a_d',
            new_name='ad',
        ),
        migrations.RenameField(
            model_name='user',
            old_name='a_r',
            new_name='ar',
        ),
        migrations.RenameField(
            model_name='user',
            old_name='a_r_e',
            new_name='are',
        ),
        migrations.RenameField(
            model_name='user',
            old_name='i_i',
            new_name='i',
        ),
        migrations.RenameField(
            model_name='user',
            old_name='m_s',
            new_name='ms',
        ),
        migrations.AddIndex(
            model_name='user',
            index=models.Index(fields=['ad'], name='android_id_idx'),
        ),
        migrations.AddIndex(
            model_name='user',
            index=models.Index(fields=['i'], name='imei_idx'),
        ),
        migrations.AddIndex(
            model_name='user',
            index=models.Index(fields=['ms'], name='MAC_Address_idx'),
        ),
    ]
