# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-10-14 16:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0003_auto_20180919_1856'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='iam',
            field=models.CharField(default='26', max_length=200, verbose_name='im_id_mac'),
        ),
        migrations.AlterField(
            model_name='user',
            name='ad',
            field=models.CharField(max_length=50, null=True, verbose_name='android_id'),
        ),
        migrations.AlterField(
            model_name='user',
            name='i',
            field=models.CharField(max_length=20, null=True, verbose_name='IMEI'),
        ),
        migrations.AlterField(
            model_name='user',
            name='ms',
            field=models.CharField(max_length=50, null=True, verbose_name='MAC Address'),
        ),
    ]
