# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-10-14 16:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0004_auto_20181014_2005'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='iam',
            field=models.CharField(max_length=200, verbose_name='im_id_mac'),
        ),
    ]
