# Generated by Django 2.1.2 on 2019-01-11 19:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0006_auto_20181030_1513'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='br',
            field=models.CharField(max_length=50, null=True, verbose_name='android_brand'),
        ),
    ]
