# Generated by Django 2.1.2 on 2019-02-03 19:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0007_user_br'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='mr',
            field=models.CharField(choices=[('0', 'Bazaar'), ('1', 'Myket'), ('2', 'NoMarket')], max_length=2, null=True, verbose_name='Market'),
        ),
    ]
