version: !!str 3

x-common-variables: &common-variables
  env_file:
    - .env

services:
  web:
    image: ${WEB_IMAGE:-none}
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - .:/app
      - static_volume:${APP_HOME}/public/static
      - media_volume:${APP_HOME}/public/media
    env_file:
      - .env
    ports:
      - "${PORT:-8000}:8000"
    depends_on:
      - db
      - redis
      - celery
    networks:
      - app_network

  db:
    image: mariadb:latest
    volumes:
      - mariadb_data:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: mysql_test
      MYSQL_DATABASE: ${DB_NAME}
      MYSQL_USER: ${DB_USER}
      MYSQL_PASSWORD: ${DB_PASSWORD}
    ports:
      - "3306:3306"
    command:
      - --character-set-server=utf8mb4
      - --collation-server=utf8mb4_unicode_ci
      - --max_allowed_packet=128M
      - --wait_timeout=28800
    networks:
      - app_network

  redis:
    image: redis:latest
    command: redis-server --appendonly yes ${REDIS_PASSWORD:+--requirepass ${REDIS_PASSWORD}}
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    networks:
      - app_network

  celery:
    image: ${WEB_IMAGE:-none}
    build:
      context: .
      dockerfile: Dockerfile
    command: celery -A ${CELERY_APP} worker -l ${LOG_LEVEL:-INFO}
    volumes:
      - .:/app
    env_file:
      - .env
    depends_on:
      - db
      - redis
    networks:
      - app_network

  flower:
    image: ${WEB_IMAGE:-none}
    build:
      context: .
      dockerfile: Dockerfile
    command: celery -A ${CELERY_APP} flower
    ports:
      - "${FLOWER_PORT:-5555}:5555"
    env_file:
      - .env
    depends_on:
      - celery
    networks:
      - app_network

volumes:
  mariadb_data:
  redis_data:
  static_volume:
  media_volume:

networks:
  app_network:
    driver: bridge