# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-09-20 06:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('log', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='request_image',
            name='log',
            field=models.TextField(verbose_name='log'),
        ),
    ]
