# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-09-20 06:53
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('log', '0002_auto_20180920_1104'),
    ]

    operations = [
        migrations.CreateModel(
            name='CashCoin',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('log', models.TextField(verbose_name='log')),
                ('createDateTime', models.DateTimeField(auto_now_add=True, verbose_name='create date')),
                ('user', models.ForeignKey(blank=True, help_text='please choose owner Coin_price', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='CashCoin', to=settings.AUTH_USER_MODEL, verbose_name='owner')),
            ],
            options={
                'verbose_name': 'CashCoin',
                'verbose_name_plural': 'CashCoin',
            },
        ),
        migrations.CreateModel(
            name='Coinvideo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('log', models.TextField(verbose_name='log')),
                ('createDateTime', models.DateTimeField(auto_now_add=True, verbose_name='create date')),
                ('user', models.ForeignKey(blank=True, help_text='please choose owner Coin_price', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Coinvideo', to=settings.AUTH_USER_MODEL, verbose_name='owner')),
            ],
            options={
                'verbose_name': 'Coinvideo',
                'verbose_name_plural': 'Coinvideo',
            },
        ),
        migrations.CreateModel(
            name='CreateUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('log', models.TextField(verbose_name='log')),
                ('createDateTime', models.DateTimeField(auto_now_add=True, verbose_name='create date')),
            ],
            options={
                'verbose_name': 'CreateUser',
                'verbose_name_plural': 'CreateUser',
            },
        ),
        migrations.CreateModel(
            name='Request_photo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('log', models.TextField(verbose_name='log')),
                ('createDateTime', models.DateTimeField(auto_now_add=True, verbose_name='create date')),
                ('user', models.ForeignKey(blank=True, help_text='please choose owner Coin_price', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Request_photo', to=settings.AUTH_USER_MODEL, verbose_name='owner')),
            ],
            options={
                'verbose_name': 'Request_photo',
                'verbose_name_plural': 'Request_photo',
            },
        ),
    ]
