# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-10-24 14:15
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('log', '0003_cashcoin_coinvideo_createuser_request_photo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='request_image',
            name='user',
        ),
        migrations.DeleteModel(
            name='Request_image',
        ),
    ]
