# Generated by Django 2.1.2 on 2018-11-03 15:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('log', '0004_auto_20181024_1745'),
    ]

    operations = [
        migrations.CreateModel(
            name='Crash',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.TextField(verbose_name='user')),
                ('log', models.TextField(verbose_name='Crash')),
                ('createDateTime', models.DateTimeField(auto_now_add=True, verbose_name='create date')),
            ],
            options={
                'verbose_name': 'Crash',
                'verbose_name_plural': 'Crash',
            },
        ),
    ]
