# Generated by Django 2.1.2 on 2018-11-03 15:36

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('photography', '0006_auto_20181103_1906'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('log', '0005_crash'),
    ]

    operations = [
        migrations.CreateModel(
            name='Photo_log',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('createDateTime', models.DateTimeField(auto_now_add=True, verbose_name='create date')),
                ('Photo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='photography.thumbnail', verbose_name='photo')),
                ('user', models.ForeignKey(blank=True, help_text='please choose owner Coin_price', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Photo_log', to=settings.AUTH_USER_MODEL, verbose_name='user')),
            ],
            options={
                'verbose_name': 'Photo_log',
                'verbose_name_plural': 'Photo_log',
            },
        ),
    ]
