# Generated by Django 2.1.2 on 2018-11-03 17:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('log', '0006_photo_log'),
    ]

    operations = [
        migrations.AlterField(
            model_name='crash',
            name='user',
            field=models.CharField(max_length=256, verbose_name='user'),
        ),
    ]
