# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-07-13 08:21
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Config',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=70, null=True, verbose_name='title')),
                ('status', models.CharField(choices=[('0', 'Draft'), ('1', 'Published')], default='0', max_length=4, verbose_name='status')),
                ('content', models.TextField(verbose_name='content')),
                ('url_pre', models.CharField(max_length=70, null=True, verbose_name='url_pre')),
                ('save_place', models.CharField(max_length=70, null=True, verbose_name='save_place')),
                ('createDateTime', models.DateTimeField(auto_now_add=True, verbose_name='create date')),
                ('updateDateTime', models.DateTimeField(auto_now=True, verbose_name='update date')),
                ('owner', models.ForeignKey(blank=True, help_text='please choose owner post', null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='owner')),
            ],
            options={
                'verbose_name': 'Config',
                'verbose_name_plural': 'Config',
            },
        ),
    ]
