# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-08-17 18:36
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='version',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField(verbose_name='content')),
                ('status', models.CharField(choices=[('0', 'Draft'), ('1', 'Published')], default='0', max_length=4, verbose_name='status')),
                ('file', models.FileField(blank=True, null=True, upload_to='', verbose_name='file')),
                ('ver_number', models.IntegerField(default=None, null=True, verbose_name='ver_number')),
                ('createDateTime', models.DateTimeField(auto_now_add=True, verbose_name='create date')),
                ('owner', models.ForeignKey(blank=True, help_text='please choose owner post', null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='owner')),
            ],
            options={
                'verbose_name': 'version',
                'verbose_name_plural': 'versions',
            },
        ),
    ]
