# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-09-02 17:08
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_version'),
    ]

    operations = [
        migrations.RenameField(
            model_name='version',
            old_name='file',
            new_name='url',
        ),
        migrations.RenameField(
            model_name='version',
            old_name='ver_number',
            new_name='ver',
        ),
    ]
