# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-09-03 18:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_auto_20180903_2144'),
    ]

    operations = [
        migrations.AddField(
            model_name='config',
            name='url',
            field=models.FileField(blank=True, null=True, upload_to='config/', verbose_name='file'),
        ),
    ]
