# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-09-03 18:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_config_url'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='config',
            name='url',
        ),
        migrations.AddField(
            model_name='config',
            name='watermark',
            field=models.FileField(blank=True, null=True, upload_to='config/', verbose_name='watermark'),
        ),
    ]
