# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-10-29 20:30
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_auto_20181029_2359'),
    ]

    operations = [
        migrations.AlterField(
            model_name='version',
            name='owner',
            field=models.ForeignKey(blank=True, default=1, help_text='please choose owner post', null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='owner'),
        ),
    ]
