# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-10-30 09:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_auto_20181030_1313'),
    ]

    operations = [
        migrations.AlterField(
            model_name='config',
            name='watermark',
            field=models.FileField(upload_to='config/', verbose_name='watermark'),
        ),
        migrations.AlterField(
            model_name='version',
            name='url',
            field=models.FileField(upload_to='version/', verbose_name='file'),
        ),
    ]
