# Generated by Django 2.1.2 on 2018-10-30 15:22

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0010_auto_20181030_1314'),
    ]

    operations = [
        migrations.AlterField(
            model_name='config',
            name='title',
            field=models.CharField(default='1', max_length=70, verbose_name='title'),
        ),
        migrations.AlterField(
            model_name='config',
            name='watermark',
            field=models.FileField(upload_to='config/', validators=[django.core.validators.FileExtensionValidator(['png'])], verbose_name='watermark'),
        ),
        migrations.AlterField(
            model_name='version',
            name='url',
            field=models.FileField(upload_to='version/', validators=[django.core.validators.FileExtensionValidator(['apk'])], verbose_name='file'),
        ),
    ]
