# Generated by Django 2.1.2 on 2018-10-30 16:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0011_auto_20181030_1852'),
    ]

    operations = [
        migrations.AlterField(
            model_name='config',
            name='title',
            field=models.CharField(max_length=70, unique=True, verbose_name='title'),
        ),
    ]
