# Generated by Django 2.1.2 on 2018-10-31 12:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0020_auto_20181031_1356'),
    ]

    operations = [
        migrations.AddField(
            model_name='config',
            name='colormap',
            field=models.TextField(default='cool', verbose_name='content'),
        ),
    ]
