# Generated by Django 2.1.2 on 2018-10-31 12:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0021_config_colormap'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='config',
            name='colormap',
        ),
    ]
