# Generated by Django 2.1.2 on 2018-11-28 09:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0023_help_app'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='config',
            name='save_place',
        ),
        migrations.RemoveField(
            model_name='config',
            name='url_pre',
        ),
    ]
