# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-10-24 14:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('category', '0004_category_order'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='category',
            index=models.Index(fields=['order'], name='order'),
        ),
    ]
