# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-10-30 09:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('category', '0006_auto_20181030_1313'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='url',
            field=models.FileField(upload_to='photography/category/', verbose_name='extra files'),
        ),
    ]
