# Generated by Django 2.1.2 on 2018-10-30 16:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('category', '0008_auto_20181030_1943'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='title',
            field=models.CharField(default='1', max_length=250, verbose_name='title'),
        ),
    ]
