# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-07-13 08:21
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('category', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='photo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=70, verbose_name='title')),
                ('order', models.PositiveIntegerField(default=1, verbose_name='order')),
                ('status', models.CharField(choices=[('0', 'Draft'), ('1', 'Published')], default='1', max_length=10, verbose_name='status')),
                ('url', models.FileField(blank=True, null=True, upload_to='images/', verbose_name='extra files')),
                ('publish', models.DateTimeField(default=django.utils.timezone.now, verbose_name='publish')),
                ('createDateTime', models.DateTimeField(auto_now_add=True, verbose_name='create date')),
                ('updateDateTime', models.DateTimeField(auto_now=True, verbose_name='update date')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='category.Category', verbose_name='category')),
                ('owner', models.ForeignKey(blank=True, help_text='please choose owner post', null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='owner')),
            ],
            options={
                'verbose_name': 'photo',
                'verbose_name_plural': 'photos',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='photo_main',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=70, verbose_name='title')),
                ('publish', models.DateTimeField(default=django.utils.timezone.now, verbose_name='publish')),
                ('url', models.FileField(blank=True, null=True, upload_to='photography/', verbose_name='extra files')),
                ('createDateTime', models.DateTimeField(auto_now_add=True, verbose_name='create date')),
                ('updateDateTime', models.DateTimeField(auto_now=True, verbose_name='update date')),
                ('owner', models.ForeignKey(blank=True, help_text='please choose owner post', null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='owner')),
            ],
            options={
                'verbose_name': 'photo_main',
                'verbose_name_plural': 'photo_main',
            },
        ),
        migrations.CreateModel(
            name='photo_Mask',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=70, verbose_name='title')),
                ('min_word', models.PositiveIntegerField(default=1000, verbose_name='min_word')),
                ('medium_word', models.PositiveIntegerField(default=500, verbose_name='medium_word')),
                ('max_word', models.PositiveIntegerField(default=100, verbose_name='max_word')),
                ('publish', models.DateTimeField(default=django.utils.timezone.now, verbose_name='publish')),
                ('url', models.FileField(blank=True, null=True, upload_to='photography/', verbose_name='extra files')),
                ('createDateTime', models.DateTimeField(auto_now_add=True, verbose_name='create date')),
                ('updateDateTime', models.DateTimeField(auto_now=True, verbose_name='update date')),
                ('owner', models.ForeignKey(blank=True, help_text='please choose owner post', null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='owner')),
            ],
            options={
                'verbose_name': 'photo_Mask',
                'verbose_name_plural': 'photo_Masks',
            },
        ),
        migrations.AddField(
            model_name='photo',
            name='photo_Mask',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='photography.photo_Mask', verbose_name='photo_Mask'),
        ),
        migrations.AddField(
            model_name='photo',
            name='photo_main',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='photography.photo_main', verbose_name='photo_main'),
        ),
    ]
