# Generated by Django 2.1.2 on 2018-10-30 16:19

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('category', '0011_auto_20181030_1949'),
        ('photography', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Photo_log',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('createDateTime', models.DateTimeField(auto_now_add=True, verbose_name='create date')),
            ],
            options={
                'verbose_name': 'Photo_log',
                'verbose_name_plural': 'Photo_log',
            },
        ),
        migrations.CreateModel(
            name='thumbnail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='title', max_length=70, unique=True, verbose_name='title')),
                ('count', models.IntegerField(default=1, verbose_name='count')),
                ('cash', models.IntegerField(default=50, verbose_name='cash')),
                ('order', models.PositiveIntegerField(default=1, verbose_name='order')),
                ('status', models.CharField(choices=[('0', 'Draft'), ('1', 'Published')], default='1', max_length=10, verbose_name='status')),
                ('url', models.FileField(default='url', upload_to='photography/thumbnail/', validators=[django.core.validators.FileExtensionValidator(['jpg'])], verbose_name='extra files')),
                ('publish', models.DateTimeField(default=django.utils.timezone.now, verbose_name='publish')),
                ('createDateTime', models.DateTimeField(auto_now_add=True, verbose_name='create date')),
                ('updateDateTime', models.DateTimeField(auto_now=True, verbose_name='update date')),
            ],
            options={
                'verbose_name': 'thumbnail',
                'verbose_name_plural': 'thumbnail',
                'ordering': ['order'],
            },
        ),
        migrations.RemoveField(
            model_name='photo',
            name='category',
        ),
        migrations.RemoveField(
            model_name='photo',
            name='owner',
        ),
        migrations.RemoveField(
            model_name='photo',
            name='photo_Mask',
        ),
        migrations.RemoveField(
            model_name='photo',
            name='photo_main',
        ),
        migrations.AlterField(
            model_name='photo_main',
            name='owner',
            field=models.ForeignKey(blank=True, default=1, help_text='please choose owner post', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='owner'),
        ),
        migrations.AlterField(
            model_name='photo_main',
            name='title',
            field=models.CharField(default='title', max_length=70, unique=True, verbose_name='title'),
        ),
        migrations.AlterField(
            model_name='photo_main',
            name='url',
            field=models.FileField(default='url', upload_to='photography/photo_main/', validators=[django.core.validators.FileExtensionValidator(['png'])], verbose_name='extra files'),
        ),
        migrations.AlterField(
            model_name='photo_mask',
            name='max_word',
            field=models.PositiveIntegerField(default=50, verbose_name='max_word'),
        ),
        migrations.AlterField(
            model_name='photo_mask',
            name='medium_word',
            field=models.PositiveIntegerField(default=100, verbose_name='medium_word'),
        ),
        migrations.AlterField(
            model_name='photo_mask',
            name='min_word',
            field=models.PositiveIntegerField(default=200, verbose_name='min_word'),
        ),
        migrations.AlterField(
            model_name='photo_mask',
            name='owner',
            field=models.ForeignKey(blank=True, default=1, help_text='please choose owner post', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='owner'),
        ),
        migrations.AlterField(
            model_name='photo_mask',
            name='title',
            field=models.CharField(default='title', max_length=70, unique=True, verbose_name='title'),
        ),
        migrations.AlterField(
            model_name='photo_mask',
            name='url',
            field=models.FileField(default='url', upload_to='photography/photo_Mask/', validators=[django.core.validators.FileExtensionValidator(['jpg'])], verbose_name='extra files'),
        ),
        migrations.AddIndex(
            model_name='photo_main',
            index=models.Index(fields=['url'], name='url'),
        ),
        migrations.AddIndex(
            model_name='photo_mask',
            index=models.Index(fields=['min_word'], name='min_word'),
        ),
        migrations.AddIndex(
            model_name='photo_mask',
            index=models.Index(fields=['medium_word'], name='medium_word'),
        ),
        migrations.AddIndex(
            model_name='photo_mask',
            index=models.Index(fields=['max_word'], name='max_word'),
        ),
        migrations.AddIndex(
            model_name='photo_mask',
            index=models.Index(fields=['url'], name='url'),
        ),
        migrations.DeleteModel(
            name='photo',
        ),
        migrations.AddField(
            model_name='thumbnail',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='thumbnail_photo', to='category.Category', verbose_name='category'),
        ),
        migrations.AddField(
            model_name='thumbnail',
            name='owner',
            field=models.ForeignKey(blank=True, default=1, help_text='please choose owner post', on_delete=django.db.models.deletion.CASCADE, related_name='thumbnail_photo', to=settings.AUTH_USER_MODEL, verbose_name='owner'),
        ),
        migrations.AddField(
            model_name='thumbnail',
            name='photo_Mask',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='photography.photo_Mask', verbose_name='photo_Mask'),
        ),
        migrations.AddField(
            model_name='thumbnail',
            name='photo_main',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='photography.photo_main', verbose_name='photo_main'),
        ),
        migrations.AddField(
            model_name='photo_log',
            name='Photo',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='photography.thumbnail', verbose_name='photo'),
        ),
        migrations.AddField(
            model_name='photo_log',
            name='user',
            field=models.ForeignKey(blank=True, help_text='please choose owner Coin_price', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Photo_log', to=settings.AUTH_USER_MODEL, verbose_name='user'),
        ),
        migrations.AddIndex(
            model_name='thumbnail',
            index=models.Index(fields=['count'], name='count'),
        ),
        migrations.AddIndex(
            model_name='thumbnail',
            index=models.Index(fields=['cash'], name='cash'),
        ),
        migrations.AddIndex(
            model_name='thumbnail',
            index=models.Index(fields=['url'], name='url'),
        ),
    ]
