# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-09-03 19:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('photography', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='photo',
            name='count',
            field=models.CharField(default='1', max_length=70, verbose_name='count'),
        ),
    ]
