# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-09-10 17:53
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('photography', '0002_photo_count'),
    ]

    operations = [
        migrations.CreateModel(
            name='Photo_log',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('createDateTime', models.DateTimeField(auto_now_add=True, verbose_name='create date')),
                ('Photo', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='photography.photo', verbose_name='photo')),
                ('user', models.ForeignKey(blank=True, help_text='please choose owner Coin_price', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Photo_log', to=settings.AUTH_USER_MODEL, verbose_name='user')),
            ],
        ),
    ]
