# Generated by Django 2.1.2 on 2018-10-30 16:23

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('photography', '0002_auto_20181030_1949'),
    ]

    operations = [
        migrations.AlterField(
            model_name='photo_main',
            name='title',
            field=models.CharField(max_length=70, unique=True, verbose_name='title'),
        ),
        migrations.AlterField(
            model_name='photo_main',
            name='url',
            field=models.FileField(upload_to='photography/photo_main/', validators=[django.core.validators.FileExtensionValidator(['png'])], verbose_name='extra files'),
        ),
        migrations.AlterField(
            model_name='photo_mask',
            name='title',
            field=models.CharField(max_length=70, unique=True, verbose_name='title'),
        ),
        migrations.AlterField(
            model_name='photo_mask',
            name='url',
            field=models.FileField(upload_to='photography/photo_Mask/', validators=[django.core.validators.FileExtensionValidator(['jpg'])], verbose_name='extra files'),
        ),
        migrations.AlterField(
            model_name='thumbnail',
            name='title',
            field=models.CharField(max_length=70, unique=True, verbose_name='title'),
        ),
        migrations.AlterField(
            model_name='thumbnail',
            name='url',
            field=models.FileField(upload_to='photography/thumbnail/', validators=[django.core.validators.FileExtensionValidator(['jpg'])], verbose_name='extra files'),
        ),
    ]
