# Generated by Django 2.1.2 on 2018-10-31 10:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('photography', '0003_auto_20181030_1953'),
    ]

    operations = [
        migrations.AlterField(
            model_name='photo_log',
            name='Photo',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='photography.thumbnail', verbose_name='photo'),
        ),
        migrations.AlterField(
            model_name='photo_mask',
            name='title',
            field=models.CharField(default=1, max_length=70, unique=True, verbose_name='title'),
        ),
        migrations.AlterField(
            model_name='thumbnail',
            name='category',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='thumbnail_photo', to='category.Category', verbose_name='category'),
        ),
        migrations.AlterField(
            model_name='thumbnail',
            name='photo_Mask',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='photography.photo_Mask', verbose_name='photo_Mask'),
        ),
        migrations.AlterField(
            model_name='thumbnail',
            name='photo_main',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='photography.photo_main', verbose_name='photo_main'),
        ),
    ]
