# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-09-10 17:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('photography', '0003_photo_log'),
    ]

    operations = [
        migrations.AlterField(
            model_name='photo',
            name='count',
            field=models.IntegerField(default=1, max_length=70, verbose_name='count'),
        ),
    ]
