# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-09-10 17:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('photography', '0004_auto_20180910_2226'),
    ]

    operations = [
        migrations.AlterField(
            model_name='photo',
            name='count',
            field=models.IntegerField(default=1, verbose_name='count'),
        ),
    ]
