# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-09-15 18:38
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('photography', '0005_auto_20180910_2227'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='photo_log',
            options={'verbose_name': 'Photo_log', 'verbose_name_plural': 'Photo_log'},
        ),
    ]
