# Generated by Django 2.1.2 on 2018-11-03 15:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('photography', '0005_auto_20181031_1352'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='photo_log',
            name='Photo',
        ),
        migrations.RemoveField(
            model_name='photo_log',
            name='user',
        ),
        migrations.DeleteModel(
            name='Photo_log',
        ),
    ]
