# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-09-26 11:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('photography', '0006_auto_20180915_2308'),
    ]

    operations = [
        migrations.AddField(
            model_name='photo',
            name='cash',
            field=models.IntegerField(default=50, verbose_name='cash'),
        ),
    ]
