# Generated by Django 2.1.2 on 2018-11-12 16:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('photography', '0006_auto_20181103_1906'),
    ]

    operations = [
        migrations.AlterField(
            model_name='thumbnail',
            name='photo_Mask',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='photography.photo_Mask', verbose_name='photo_Mask'),
        ),
        migrations.AlterField(
            model_name='thumbnail',
            name='photo_main',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='photography.photo_main', verbose_name='photo_main'),
        ),
    ]
