# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-09-30 21:01
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('photography', '0007_photo_cash'),
    ]

    operations = [
        migrations.AlterField(
            model_name='photo',
            name='owner',
            field=models.ForeignKey(blank=True, default=1, help_text='please choose owner post', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='owner'),
        ),
        migrations.AlterField(
            model_name='photo_main',
            name='owner',
            field=models.ForeignKey(blank=True, default=1, help_text='please choose owner post', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='owner'),
        ),
        migrations.AlterField(
            model_name='photo_mask',
            name='owner',
            field=models.ForeignKey(blank=True, default=1, help_text='please choose owner post', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='owner'),
        ),
    ]
