# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-10-03 07:52
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('category', '0002_auto_20181001_0029'),
        ('photography', '0008_auto_20181001_0031'),
    ]

    operations = [
        migrations.CreateModel(
            name='thumbnail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=70, verbose_name='title')),
                ('count', models.IntegerField(default=1, verbose_name='count')),
                ('cash', models.IntegerField(default=50, verbose_name='cash')),
                ('order', models.PositiveIntegerField(default=1, verbose_name='order')),
                ('status', models.CharField(choices=[('0', 'Draft'), ('1', 'Published')], default='1', max_length=10, verbose_name='status')),
                ('url', models.FileField(blank=True, null=True, upload_to='images/', verbose_name='extra files')),
                ('publish', models.DateTimeField(default=django.utils.timezone.now, verbose_name='publish')),
                ('createDateTime', models.DateTimeField(auto_now_add=True, verbose_name='create date')),
                ('updateDateTime', models.DateTimeField(auto_now=True, verbose_name='update date')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='thumbnail_photo', to='category.Category', verbose_name='category')),
                ('owner', models.ForeignKey(blank=True, default=1, help_text='please choose owner post', on_delete=django.db.models.deletion.CASCADE, related_name='thumbnail_photo', to=settings.AUTH_USER_MODEL, verbose_name='owner')),
                ('photo_Mask', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='photography.photo_Mask', verbose_name='photo_Mask')),
                ('photo_main', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='photography.photo_main', verbose_name='photo_main')),
            ],
            options={
                'verbose_name': 'thumbnail',
                'verbose_name_plural': 'thumbnail',
                'ordering': ['order'],
            },
        ),
        migrations.RemoveField(
            model_name='photo',
            name='category',
        ),
        migrations.RemoveField(
            model_name='photo',
            name='owner',
        ),
        migrations.RemoveField(
            model_name='photo',
            name='photo_Mask',
        ),
        migrations.RemoveField(
            model_name='photo',
            name='photo_main',
        ),
        migrations.AlterField(
            model_name='photo_log',
            name='Photo',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='photography.thumbnail', verbose_name='photo'),
        ),
        migrations.DeleteModel(
            name='photo',
        ),
    ]
