# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-10-23 15:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('photography', '0010_auto_20181012_1729'),
    ]

    operations = [
        migrations.AlterField(
            model_name='photo_main',
            name='url',
            field=models.FileField(blank=True, null=True, upload_to='photography/photo_main/', verbose_name='extra files'),
        ),
        migrations.AlterField(
            model_name='photo_mask',
            name='url',
            field=models.FileField(blank=True, null=True, upload_to='photography/photo_Mask/', verbose_name='extra files'),
        ),
        migrations.AlterField(
            model_name='thumbnail',
            name='url',
            field=models.FileField(blank=True, null=True, upload_to='photography/thumbnail/', verbose_name='extra files'),
        ),
    ]
