# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-10-23 15:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('photography', '0011_auto_20181023_1833'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='photo_main',
            index=models.Index(fields=['url'], name='url'),
        ),
        migrations.AddIndex(
            model_name='photo_mask',
            index=models.Index(fields=['min_word'], name='min_word'),
        ),
        migrations.AddIndex(
            model_name='photo_mask',
            index=models.Index(fields=['medium_word'], name='medium_word'),
        ),
        migrations.AddIndex(
            model_name='photo_mask',
            index=models.Index(fields=['max_word'], name='max_word'),
        ),
        migrations.AddIndex(
            model_name='photo_mask',
            index=models.Index(fields=['url'], name='url'),
        ),
        migrations.AddIndex(
            model_name='thumbnail',
            index=models.Index(fields=['count'], name='count'),
        ),
        migrations.AddIndex(
            model_name='thumbnail',
            index=models.Index(fields=['cash'], name='cash'),
        ),
        migrations.AddIndex(
            model_name='thumbnail',
            index=models.Index(fields=['url'], name='url'),
        ),
    ]
