# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-10-30 09:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('photography', '0013_auto_20181030_1308'),
    ]

    operations = [
        migrations.AlterField(
            model_name='thumbnail',
            name='url',
            field=models.FileField(upload_to='photography/thumbnail/', verbose_name='extra files'),
        ),
    ]
