# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-10-30 09:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('photography', '0014_auto_20181030_1308'),
    ]

    operations = [
        migrations.AlterField(
            model_name='photo_main',
            name='url',
            field=models.FileField(default='1', upload_to='photography/photo_main/', verbose_name='extra files'),
        ),
        migrations.AlterField(
            model_name='photo_mask',
            name='url',
            field=models.FileField(default='1', upload_to='photography/photo_Mask/', verbose_name='extra files'),
        ),
    ]
