# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-10-30 09:52
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('photography', '0016_auto_20181030_1312'),
    ]

    operations = [
        migrations.AlterField(
            model_name='photo_main',
            name='url',
            field=models.FileField(upload_to='photography/photo_main/', validators=[django.core.validators.FileExtensionValidator(['png'])], verbose_name='extra files'),
        ),
    ]
