# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-10-30 09:54
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('photography', '0017_auto_20181030_1322'),
    ]

    operations = [
        migrations.AlterField(
            model_name='photo_mask',
            name='url',
            field=models.FileField(upload_to='photography/photo_Mask/', validators=[django.core.validators.FileExtensionValidator(['jpg'])], verbose_name='extra files'),
        ),
        migrations.AlterField(
            model_name='thumbnail',
            name='url',
            field=models.FileField(upload_to='photography/thumbnail/', validators=[django.core.validators.FileExtensionValidator(['jpg'])], verbose_name='extra files'),
        ),
    ]
