# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-09-09 17:53
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Coin_price',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('coin_price', models.IntegerField(default=0, verbose_name='coin_price')),
                ('createDateTime', models.DateTimeField(auto_now_add=True, verbose_name='create date')),
                ('user', models.OneToOneField(blank=True, help_text='please choose owner Coin_price', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Coin_price', to=settings.AUTH_USER_MODEL, verbose_name='owner')),
            ],
        ),
        migrations.CreateModel(
            name='Coin_video',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('coin_video', models.IntegerField(default=0, verbose_name='Coin_video')),
                ('createDateTime', models.DateTimeField(auto_now_add=True, verbose_name='create date')),
                ('user', models.OneToOneField(blank=True, help_text='please choose owner Coin_video', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Coin_video', to=settings.AUTH_USER_MODEL, verbose_name='owner')),
            ],
        ),
    ]
